# Ultralytics YOLO 🚀, AGPL-3.0 license
# Modified BoT-SORT settings for event camera data

tracker_type: botsort
track_buffer: 300  

track_high_thresh: 0.2  
track_low_thresh: 0.05 
new_track_thresh: 0.2   

match_thresh: 0.9  

fuse_score: True

gmc_method: sparseOptFlow  

proximity_thresh: 0.7  

appearance_thresh: 0.35  

with_reid: True